/* Date Created: 29/03/2026. */

//! Note, rendered HTML in note are generated by https://spec.commonmark.org/dingus/
//! 
//! This is an authoritative tool by the CommonMark Project.

#![allow(dead_code)]

// These are from 
// https://github.com/behai-nguyen/polyglot_pdf/blob/main/pdf_06_text_styling/src/inline_parser.rs
// -- All constants renamed.
pub const HEADER_01: &str = "# Thỏa Hiệp Án Fontainebleau 14/09/1946: ông Hồ \
    cấu kết với Pháp để tiêu diệt các đảng quốc gia.";
pub const HEADER_01_TEXT: &str = "Thỏa Hiệp Án Fontainebleau 14/09/1946: ông \
    Hồ cấu kết với Pháp để tiêu diệt các đảng quốc gia.";

pub const HEADER_02: &str = "## Kéo rốc sang Pháp làm gì?";
pub const HEADER_02_TEXT: &str = "Kéo rốc sang Pháp làm gì?";

// `<h1><strong>Thỏa Hiệp Án <em>Fontainebleau 14/09/1946</em>: ông Hồ 
//      cấu kết với Pháp để <em>tiêu diệt</em> các đảng quốc gia.</strong></h1>`
pub const HEADER_03: &str = "# **Thỏa Hiệp Án *Fontainebleau 14/09/1946*: ông Hồ \
    cấu kết với Pháp để *tiêu diệt* các đảng quốc gia.**";
pub const HEADER_03_TEXT: &str = "Thỏa Hiệp Án Fontainebleau 14/09/1946: ông \
    Hồ cấu kết với Pháp để tiêu diệt các đảng quốc gia.";

// Test `TokenType::Whitespace` get removed from final text.
pub const HEADER_04: &str = "#     **Thỏa Hiệp Án *Fontainebleau 14/09/1946*: \
    ông Hồ cấu kết với Pháp để *tiêu diệt* các đảng quốc gia.**";
pub const HEADER_04_TEXT: &str = "Thỏa Hiệp Án Fontainebleau 14/09/1946: ông \
    Hồ cấu kết với Pháp để tiêu diệt các đảng quốc gia.";

pub const HEADER_05: &str = "####    ";
pub const HEADER_06: &str = "###";

pub const HASH_ESCAPE_01: &str = "\\# Giấc Mơ Trường Sơn";
pub const HASH_ESCAPE_01_TEXT: &str = "# Giấc Mơ Trường Sơn";

pub const HASH_ESCAPE_02: &str = "Giấc Mơ Trường Sơn \\# Tuệ Sỹ";
pub const HASH_ESCAPE_02_TEXT: &str = "Giấc Mơ Trường Sơn # Tuệ Sỹ";

pub const HEADER_HASH_ESCAPE_01: &str = "# ABC \\# Ô ô Ơ ơ \\# Ư ư Ứ ứ";
pub const HEADER_HASH_ESCAPE_01_TEXT: &str = "ABC # Ô ô Ơ ơ # Ư ư Ứ ứ";

// These `HEADER_INVALID_*` were added after `Parser::header()` has 
// been written.
pub const HEADER_INVALID_01: &str = "####### Giấc Mơ Trường Sơn \\# Tuệ Sỹ";
pub const HEADER_INVALID_01_PARSED_TEXT: &str = "####### Giấc Mơ Trường Sơn # Tuệ Sỹ";

pub const HEADER_INVALID_02: &str = "######## **Thỏa Hiệp Án *Fontainebleau \
    14/09/1946*: ông Hồ cấu kết với Pháp để *tiêu diệt* các đảng quốc gia.**";
pub const HEADER_INVALID_02_PARSED_TEXT: &str = "######## Thỏa Hiệp Án Fontainebleau \
    14/09/1946: ông Hồ cấu kết với Pháp để tiêu diệt các đảng quốc gia.";

pub const HEADER_INVALID_03: &str = "#Thỏa Hiệp Án Fontainebleau 14/09/1946: ông Hồ \
    cấu kết với Pháp để tiêu diệt các đảng quốc gia.";

pub const HEADER_INVALID_04: &str = "###*Giấc Mơ Trường Sơn*";
pub const HEADER_INVALID_04_PARSED_TEXT: &str = "###Giấc Mơ Trường Sơn";

// `— <strong>Tưởng Vĩnh Kính</strong>, Hồ Chí Minh Tại <em>Trung Quốc</em>, Thượng Huyền dịch, <em><strong>trang 339</strong></em>.`
pub const ASTERISK_01: &str = "— **Tưởng Vĩnh Kính**, Hồ Chí Minh Tại *Trung Quốc*, \
    Thượng Huyền dịch, ***trang 339***.";
pub const ASTERISK_01_PARSED_TEXT: &str = "— Tưởng Vĩnh Kính, Hồ Chí Minh Tại \
    Trung Quốc, Thượng Huyền dịch, trang 339.";

// `— <strong>Tưởng Vĩnh Kính</strong>, Hồ Chí Minh Tại <em>Trung Quốc</em>, Thượng Huyền dịch, <em><strong>trang 339</strong></em>.*`
pub const ASTERISK_02: &str = "— **Tưởng Vĩnh Kính**, Hồ Chí Minh Tại *Trung Quốc*, \
    Thượng Huyền dịch, ***trang 339***.*";
pub const ASTERISK_02_PARSED_TEXT: &str = "— Tưởng Vĩnh Kính, Hồ Chí Minh Tại \
    Trung Quốc, Thượng Huyền dịch, trang 339.*";

// `<strong>Tưởng Vĩnh Kính</strong>*`
pub const ASTERISK_03: &str = "**Tưởng Vĩnh Kính***";
pub const ASTERISK_03_SCANNED_TEXT: &str = "Tưởng Vĩnh Kính";
pub const ASTERISK_03_PARSED_TEXT: &str = "Tưởng Vĩnh Kính*";

// `*<strong>Tưởng Vĩnh Kính</strong>`
pub const ASTERISK_04: &str = "***Tưởng Vĩnh Kính**";
pub const ASTERISK_04_SCANNED_TEXT: &str = "Tưởng Vĩnh Kính";
pub const ASTERISK_04_PARSED_TEXT: &str = "*Tưởng Vĩnh Kính";

// `**<em>Tưởng Vĩnh Kính</em>`
pub const ASTERISK_05: &str = "***Tưởng Vĩnh Kính*";
pub const ASTERISK_05_SCANNED_TEXT: &str = "Tưởng Vĩnh Kính";
pub const ASTERISK_05_PARSED_TEXT: &str = "**Tưởng Vĩnh Kính";

// `Tưởng Vĩnh Kính \(\*\)`
pub const ASTERISK_06: &str = "Tưởng Vĩnh Kính \\(\\*\\)";
pub const ASTERISK_06_PARSED_TEXT: &str = "Tưởng Vĩnh Kính (*)";

// Special can_open, can_close.
// `<em><strong>bold</strong></em>text<strong>more</strong>`
pub const ASTERISK_07: &str = "***bold***text**more**";
pub const ASTERISK_07_PARSED_TEXT: &str = "boldtextmore";

// `<em><strong>bold</strong></em> *`
pub const ASTERISK_08: &str = r"***bold*** \*";
pub const ASTERISK_08_PARSED_TEXT: &str = "bold *";

pub const ASTERISK_09: &str = r"\*not italic\*";
pub const ASTERISK_09_PARSED_TEXT: &str = "*not italic*";

// `<strong>bold *inside*</strong>`
pub const ASTERISK_10: &str = r"**bold \*inside\***";
pub const ASTERISK_10_PARSED_TEXT: &str = "bold *inside*";

// `\Úc Đại Lợi\`
pub const ASTERISK_11: &str = r"\\Úc Đại Lợi\\";
pub const ASTERISK_11_PARSED_TEXT: &str = r"\Úc Đại Lợi\";

// `<strong>bold \Úc Đại Lợi\</strong>`
pub const ASTERISK_12: &str = r"**bold \\Úc Đại Lợi\\**";
pub const ASTERISK_12_PARSED_TEXT: &str = r"bold \Úc Đại Lợi\";

// `<strong>bold <em>italic inside bold</em> bold</strong>`
pub const ASTERISK_13: &str = "**bold *italic inside bold* bold**";
pub const ASTERISK_13_PARSED_TEXT: &str = "bold italic inside bold bold";

// `<strong>Không đọc <em>sử</em> không đủ tư cách nói chuyện <em>chính trị</em>.</strong>`
pub const ASTERISK_14: &str = "**Không đọc *sử* không đủ tư cách nói chuyện *chính trị*.**";
pub const ASTERISK_14_PARSED_TEXT: &str = "Không đọc sử không đủ tư cách nói chuyện chính trị.";

// Previous Name: MARKDOWN_BUG_01.
// `\( <strong>Chính Ðạo, <em>Việt Nam Niên Biểu</em>, <em>Tập 1A</em></strong>, trang 347 \)`
pub const ASTERISK_15: &str = r"\\( **Chính Ðạo, *Việt Nam Niên Biểu*, *Tập 1A***, trang 347 \\)";
pub const ASTERISK_15_PARSED_TEXT: &str = "\\( Chính Ðạo, Việt Nam Niên Biểu, Tập 1A, trang 347 \\)";

// Previous Name: MARKDOWN_BUG_02.
// `<em><strong>bold</strong></em>`
pub const ASTERISK_16: &str = "***bold***";
pub const ASTERISK_16_PARSED_TEXT: &str = "bold";

// Previous Name: MARKDOWN_BUG_03.
// `<strong>xy, <em>bc</em>, <em>de</em></strong>`
pub const ASTERISK_17: &str = "**xy, *bc*, *de***";
pub const ASTERISK_17_PARSED_TEXT: &str = "xy, bc, de";

// Previous Name: MARKDOWN_BUG_04.
// `<strong><em>xy</em> z</strong>`
pub const ASTERISK_18: &str = "***xy* z**";
pub const ASTERISK_18_PARSED_TEXT: &str = "xy z";

// Previous Name: MARKDOWN_BUG_05.
// `.* <strong>Tưởng Vĩnh Kính</strong>*`
pub const ASTERISK_19: &str = ".* **Tưởng Vĩnh Kính***";
pub const ASTERISK_19_PARSED_TEXT: &str = ".* Tưởng Vĩnh Kính*";

// `<em><strong>bold</strong></em> text <strong>more</strong>`
pub const ASTERISK_20: &str = "***bold*** text **more**";
pub const ASTERISK_20_PARSED_TEXT: &str = "bold text more";

// Special: can_open, can_close.
// `<em><strong>bold</strong></em>more`
pub const ASTERISK_21: &str = "***bold***more";
pub const ASTERISK_21_PARSED_TEXT: &str = "boldmore";

// `<em><strong>bold</strong></em>  more`
pub const ASTERISK_22: &str = "***bold***  more";
pub const ASTERISK_22_PARSED_TEXT: &str = "bold  more";

// `<em><strong>bold</strong></em>\nmore`
pub const ASTERISK_23: &str = "***bold***\nmore";
pub const ASTERISK_23_PARSED_TEXT: &str = "bold\nmore";

// `<em><strong>bold</strong></em>\tmore`
pub const ASTERISK_24: &str = "***bold***\tmore";
pub const ASTERISK_24_PARSED_TEXT: &str = "bold\tmore";

// `<em><strong>bold</strong></em>*more`
pub const ASTERISK_25: &str = "***bold***\\*more";
pub const ASTERISK_25_PARSED_TEXT: &str = "bold*more";

// See also ASTERISK_03, ASTERISK_04 and ASTERISK_05.
// `*<strong><strong>Tưởng Vĩnh Kính</strong></strong>`
pub const ASTERISK_26: &str = "*****Tưởng Vĩnh Kính****";
pub const ASTERISK_26_SCANNED_TEXT: &str = "Tưởng Vĩnh Kính";
pub const ASTERISK_26_PARSED_TEXT: &str = "*Tưởng Vĩnh Kính";

pub const RECURRING_ESCAPE_01: &str = r"\\abc\\ de \a";
pub const RECURRING_ESCAPE_01_TEXT: &str = r"\abc\ de \a";

// In `tests/test_parser.rs` only. It is a block element.
pub const RECURRING_ESCAPE_02: &str = r"# Giấc Mơ Trường \# Sơn \T";
pub const RECURRING_ESCAPE_02_TEXT: &str = r"Giấc Mơ Trường # Sơn \T";

pub const ESCAPE_NEWLINE_01: &str = r"Giấc Mơ Trường Sơn \\n Tuệ Sỹ.";
// Purposely removed "PARSED_".
pub const ESCAPE_NEWLINE_01_TEXT: &str = r"Giấc Mơ Trường Sơn \n Tuệ Sỹ.";

// Escaped backslashes inside emphasis (`\\*bold\\*`). 
// Final clean text: "*bold*".
pub const ESCAPE_INSIDE_EMPHASIS_01: &str = "\\*bold\\*";
pub const ESCAPE_INSIDE_EMPHASIS_01_TEXT: &str = "*bold*";

// Emphasis markers adjacent to escaped characters (`*\*bold\**`).
// `<em>*bold*</em>`
pub const EMPHASIS_ADJACENT_ESCAPE_01: &str = r"*\*bold\**";
pub const EMPHASIS_ADJACENT_ESCAPE_01_TEXT: &str = "*bold*";

// In the previous parser:
//
// ● Bold nested inside italic: for example, `*-- **Sir John Seeley**, 1885*` 
// is not supported. It results in `-- Sir John Seeley, 1885` in italic.
// https://behai-nguyen.github.io/2026/02/23/pdf-09-pango-supporting-text-styling.html#the-parser-known-limitations
// `<em>-- <strong>Sir John Seeley</strong>, 1885</em>`
pub const EMPHASIS_BOLD_INSIDE_ITALIC_01: &str = "*-- **Sir John Seeley**, 1885*";
pub const EMPHASIS_BOLD_INSIDE_ITALIC_01_PARSED_TEXT: &str = "-- Sir John Seeley, 1885";

// `— See <em>-- <strong>Sir John Seeley</strong>, 1885</em>`
pub const EMPHASIS_BOLD_INSIDE_ITALIC_02: &str = "— See *-- **Sir John Seeley**, 1885*";
pub const EMPHASIS_BOLD_INSIDE_ITALIC_02_PARSED_TEXT: &str = "— See -- Sir John Seeley, 1885";

// `[<strong>Đây Là Chú Thích Của Hình</strong>`
pub const EMPHASIS_UNEVEN_TOKEN_01: &str = "[**Đây Là Chú Thích Của Hình**";
pub const EMPHASIS_UNEVEN_TOKEN_01_PARSED_TEXT: &str = "[Đây Là Chú Thích Của Hình";

// `<strong>Đây Là Chú Thích Của Hình</strong>]`
pub const EMPHASIS_UNEVEN_TOKEN_02: &str = "**Đây Là Chú Thích Của Hình**]";
pub const EMPHASIS_UNEVEN_TOKEN_02_PARSED_TEXT: &str = "Đây Là Chú Thích Của Hình]";

// `(<strong>Đây Là Chú Thích Của Hình</strong>`
pub const EMPHASIS_UNEVEN_TOKEN_03: &str = "(**Đây Là Chú Thích Của Hình**";
pub const EMPHASIS_UNEVEN_TOKEN_03_PARSED_TEXT: &str = "(Đây Là Chú Thích Của Hình";

// `<strong>Đây Là Chú Thích Của Hình</strong>)`
pub const EMPHASIS_UNEVEN_TOKEN_04: &str = "**Đây Là Chú Thích Của Hình**)";
pub const EMPHASIS_UNEVEN_TOKEN_04_PARSED_TEXT: &str = "Đây Là Chú Thích Của Hình)";

// These are from 
// https://github.com/behai-nguyen/polyglot_pdf/blob/main/pdf_09_image_block/src/image_block_parser.rs
// -- All constants renamed.
pub const IMAGE_BLOCK_01: &str = "![](relative/path/to/image.png)";
#[allow(dead_code)]
pub const IMAGE_BLOCK_01_CAPTION: &str = "";
pub const IMAGE_BLOCK_01_PATH: &str = "relative/path/to/image.png";

pub const IMAGE_BLOCK_02: &str = "![Đây Là Chú Thích Của Hình](relative/path/to/image.png)";
pub const IMAGE_BLOCK_02_CAPTION: &str = "Đây Là Chú Thích Của Hình";
pub const IMAGE_BLOCK_02_PATH: &str = "relative/path/to/image.png";

pub const IMAGE_BLOCK_03: &str = "![Đây Là Con Chim Cassowary](./img/139015.png)";
pub const IMAGE_BLOCK_03_CAPTION: &str = "Đây Là Con Chim Cassowary";
pub const IMAGE_BLOCK_03_PATH: &str = "./img/139015.png";

// TO_DO: `_` will need to be revisited when supported.
pub const IMAGE_BLOCK_04: &str = "![Đây Là Con Chim Cassowary]\
    (F:/rust/polyglot_pdf/pdf_08_image_layout/img/139015.png)";
pub const IMAGE_BLOCK_04_CAPTION: &str = "Đây Là Con Chim Cassowary";
pub const IMAGE_BLOCK_04_PATH: &str = "F:/rust/polyglot_pdf/pdf_08_image_layout/img/139015.png";

pub const IMAGE_BLOCK_MULTILINE_01: &str = "![Cassowary, an Australia native, \
    and “the world's most dangerous bird”.\nCassowary, chim bản địa Úc, và là \
    “loài chim nguy hiểm nhất thế giới”.](./img/139015.png)";
pub const IMAGE_BLOCK_MULTILINE_01_PATH: &str = "./img/139015.png";
pub const IMAGE_BLOCK_MULTILINE_01_CAPTION: &str = "Cassowary, an Australia native, \
    and “the world's most dangerous bird”.\nCassowary, chim bản địa Úc, và là \
    “loài chim nguy hiểm nhất thế giới”.";

pub const IMAGE_BLOCK_MULTI_LINGUAL: &str = "![Mount Fuji / 富士山, ふじさ, Fujisan / \
    Núi Phú Sỹ](./img/fujisan.png)";
pub const IMAGE_BLOCK_MULTI_LINGUAL_CAPTION: &str = "Mount Fuji / 富士山, ふじさ, Fujisan / \
    Núi Phú Sỹ";
pub const IMAGE_BLOCK_MULTI_LINGUAL_PATH: &str = "./img/fujisan.png";

// Invalid image blocks, not so much at the scanning stage, possibly at a later.
// Included them in scanner tests for the shake of completeness.
pub const IMAGE_BLOCK_INVALID_01: &str = "!Đây Là Chú Thích Của Hình](relative/path/to/image.png)";
pub const IMAGE_BLOCK_INVALID_02: &str = "![Đây Là Chú Thích Của Hình(relative/path/to/image.png)";
pub const IMAGE_BLOCK_INVALID_03: &str = "![Đây Là Chú Thích Của Hình]relative/path/to/image.png)";
pub const IMAGE_BLOCK_INVALID_04: &str = "![Đây Là Chú Thích Của Hình](relative/path/to/image.png";
pub const IMAGE_BLOCK_INVALID_05: &str = "![Đây Là Chú Thích Của Hình]()";
// Ends pdf_09_image_block/src/image_block_parser.rs.

pub const IMAGE_BLOCK_INVALID_06: &str = "!***Mount Fuji* / *富士山, ふじさ, \
    Fujisan* / *Núi Phú Sỹ***](./img/fujisan.png)";
pub const IMAGE_BLOCK_INVALID_06_PARSED_TEXT: &str = "!Mount Fuji / 富士山, ふじさ, \
    Fujisan / Núi Phú Sỹ](./img/fujisan.png)";

pub const IMAGE_BLOCK_INVALID_07: &str = "![line 1\nline 2\nline 3](./img/139015.png";
pub const IMAGE_BLOCK_INVALID_08: &str = "! [Núi Phú Sỹ](./img/fujisan.png)";

// Caption with **leading/trailing spaces** on lines.
// CommonMark: `<img src="./img/139015.png" alt="  Đây Là Con Chim Cassowary " />`
pub const IMAGE_BLOCK_05: &str = "![  Đây Là Con Chim Cassowary ](./img/139015.png)";
pub const IMAGE_BLOCK_05_CAPTION: &str = "  Đây Là Con Chim Cassowary ";
pub const IMAGE_BLOCK_05_PATH: &str = "./img/139015.png";

// Captions containing literal `(` or `)` without escapes.
pub const IMAGE_BLOCK_06: &str = "![(abc)](./img/test.png)";
pub const IMAGE_BLOCK_06_CAPTION: &str = "(abc)";
pub const IMAGE_BLOCK_06_PATH: &str = "./img/test.png";

pub const IMAGE_BLOCK_MULTILINE_02: &str = "![BẠCH ĐẰNG HẢI KHẨU\n\
    Sóc phong xuy hải khí lăng lăng,\n\
    Khinh khởi ngâm phàm quá Bạch Đằng.\n\
    Ngạc đoạn kình khoa sơn khúc khúc,\n\
    Qua trầm kích chiết ngạn tằng tằng.\n\
    Quan hà bách nhị do thiên thiết,\n\
    Hào kiệt công danh thử địa tằng.\n\
    Vãng sự hồi đầu ta dĩ hĩ,\n\
    Lâm lưu phủ cảnh ý nan thăng.\n\
    -- Ức Trai Nguyễn Trãi](E:/images/bach-dang-river.png)";
pub const IMAGE_BLOCK_MULTILINE_02_PATH: &str = "E:/images/bach-dang-river.png";
pub const IMAGE_BLOCK_MULTILINE_02_CAPTION: &str = "BẠCH ĐẰNG HẢI KHẨU\n\
    Sóc phong xuy hải khí lăng lăng,\n\
    Khinh khởi ngâm phàm quá Bạch Đằng.\n\
    Ngạc đoạn kình khoa sơn khúc khúc,\n\
    Qua trầm kích chiết ngạn tằng tằng.\n\
    Quan hà bách nhị do thiên thiết,\n\
    Hào kiệt công danh thử địa tằng.\n\
    Vãng sự hồi đầu ta dĩ hĩ,\n\
    Lâm lưu phủ cảnh ý nan thăng.\n\
    -- Ức Trai Nguyễn Trãi";

// Captions with **blank lines** (two consecutive newlines).
pub const IMAGE_BLOCK_MULTILINE_03: &str = "![\n\n](./img/test.png)";
pub const IMAGE_BLOCK_MULTILINE_03_CAPTION: &str = "\n\n";
pub const IMAGE_BLOCK_MULTILINE_03_PATH: &str = "./img/test.png";

pub const IMAGE_BLOCK_WIN_STYLE: &str = "![Tại tư gia của Marius Moutet]\
    (F:\\rust\\polyglot\\_pdf\\pdf\\_09\\_image\\_block\\text\\img - \
    Copy \\(2\\)\\ho-chi-minh-marius-moutet-19460914.png)";
pub const IMAGE_BLOCK_WIN_STYLE_CAPTION: &str = "Tại tư gia của Marius Moutet";
pub const IMAGE_BLOCK_WIN_STYLE_PATH: &str = "F:\\rust\\polyglot_pdf\\pdf_09_image_\
    block\\text\\img - Copy (2)\\ho-chi-minh-marius-moutet-19460914.png";

pub const IMAGE_BLOCK_ESCAPE_01: &str = "![Mount Fuji / \\(富士山, ふじさ, \
    Fujisan\\) / \\[Núi Phú Sỹ\\]](./img/fujisan.png)";
pub const IMAGE_BLOCK_ESCAPE_01_CAPTION: &str = "Mount Fuji / (富士山, ふじさ, \
    Fujisan) / [Núi Phú Sỹ]";
pub const IMAGE_BLOCK_ESCAPE_01_PATH: &str = "./img/fujisan.png";

pub const IMAGE_BLOCK_ESCAPE_02: &str = "![Mount Fuji\\! So Beautiful\\!]\
    (./img/fujisan.png)";
pub const IMAGE_BLOCK_ESCAPE_02_CAPTION: &str = "Mount Fuji! So Beautiful!";
pub const IMAGE_BLOCK_ESCAPE_02_PATH: &str = "./img/fujisan.png";

// Captions with **escaped newlines** (`\\n`).
pub const IMAGE_BLOCK_ESCAPE_03: &str = "![Đây Là Con Chim \
    Cassowary\\nÚc Đại Lợi](./img/139015.png)";
pub const IMAGE_BLOCK_ESCAPE_03_CAPTION: &str = "Đây Là Con Chim \
    Cassowary\\nÚc Đại Lợi";
pub const IMAGE_BLOCK_ESCAPE_03_PATH: &str = "./img/139015.png";

// Captions containing: literal backslashes (`\\`),  escaped stars (`\*`), 
// escaped bangs (`\!`).
pub const IMAGE_BLOCK_ESCAPE_04: &str = "![AÀÁ \\ E Ê Ề \\* \
    Ù Ú Ụ \\! Đ D](./img/test.png)";
pub const IMAGE_BLOCK_ESCAPE_04_CAPTION: &str = r"AÀÁ \ E Ê Ề * Ù Ú Ụ ! Đ D";
pub const IMAGE_BLOCK_ESCAPE_04_PATH: &str = "./img/test.png";

// Captions containing `]` at the very end (`\]`).
pub const IMAGE_BLOCK_ESCAPE_05: &str = "![\\[ AÀÁ E Ê Ề \\]](./img/test.png)";
pub const IMAGE_BLOCK_ESCAPE_05_CAPTION: &str = r"[ AÀÁ E Ê Ề ]";
pub const IMAGE_BLOCK_ESCAPE_05_PATH: &str = "./img/test.png";

pub const IMAGE_BLOCK_EMPHASIS_01: &str = "![***Mount Fuji* / *富士山, ふじさ, \
    Fujisan* / *Núi Phú Sỹ***](./img/fujisan.png)";
pub const IMAGE_BLOCK_EMPHASIS_01_CAPTION: &str = "Mount Fuji / 富士山, ふじさ, \
    Fujisan / Núi Phú Sỹ";
pub const IMAGE_BLOCK_EMPHASIS_01_PATH: &str = "./img/fujisan.png";

// Captions containing nested emphasis (`***a *b* c***`).
// `<em><strong>a <em>b</em> c</strong></em>`
pub const IMAGE_BLOCK_NESTED_EMPHASIS_01: &str = "![***a *b* c***](./img/test.png)";
pub const IMAGE_BLOCK_NESTED_EMPHASIS_01_CAPTION: &str = "a b c";
pub const IMAGE_BLOCK_NESTED_EMPHASIS_01_PATH: &str = "./img/test.png";

// Captions containing both escapes and emphasis markers.
pub const IMAGE_BLOCK_EMPHASIS_ESCAPE_01: &str = "![***Mount Fuji* / *富士山, ふじさ, \
    Fujisan* / *\\(Núi Phú Sỹ\\)***](./img/fujisan.png)";
pub const IMAGE_BLOCK_EMPHASIS_ESCAPE_01_CAPTION: &str = "Mount Fuji / 富士山, ふじさ, \
    Fujisan / (Núi Phú Sỹ)";
pub const IMAGE_BLOCK_EMPHASIS_ESCAPE_01_PATH: &str = "./img/fujisan.png";

// More than one image block on the same line: still not supported.
// The first is recognised as image block, the second one is just text.
// Block element must start on a new line.
// https://behai-nguyen.github.io/2026/03/25/pdf-12-pango-supporting-image-block.html#image-block-parser-limitations
pub const IMAGE_BLOCK_MULTI_ITEMS_01: &str = "![a b c](./img/test1.png)\
    ![Á Ừ Ứ](./img/test2.png)";
pub const IMAGE_BLOCK_MULTI_ITEMS_01_CAPTION_01: &str = "a b c";
pub const IMAGE_BLOCK_MULTI_ITEMS_01_PATH_01: &str = "./img/test1.png";

// One image block after another on two new lines: block element must 
// start on a new line.
pub const IMAGE_BLOCK_MULTI_ITEMS_02: &str = "![a b c](./img/test1.png)\n\
    ![Á Ừ Ứ](./img/test2.png)";
pub const IMAGE_BLOCK_MULTI_ITEMS_02_CAPTION_01: &str = "a b c";
pub const IMAGE_BLOCK_MULTI_ITEMS_02_PATH_01: &str = "./img/test1.png";
pub const IMAGE_BLOCK_MULTI_ITEMS_02_CAPTION_02: &str = "Á Ừ Ứ";
pub const IMAGE_BLOCK_MULTI_ITEMS_02_PATH_02: &str = "./img/test2.png";

pub const IMAGE_BLOCK_ADJACENT_TEXT_01: &str = "![a](x)text";

/// These are the captions of some image blocks defined above, these captions 
/// are special, such as: multilines, recurring escape, emphasis, etc. They 
/// are defined here to test the [`md_parser::parser::delimiter::DelimiterParser`] 
/// various methods.

// From: IMAGE_BLOCK_MULTILINE_01
pub const MULTILINE_LINE_CAPTION_01: &str = "Cassowary, an Australia native, \
    and “the world's most dangerous bird”.\nCassowary, chim bản địa Úc, \
    và là “loài chim nguy hiểm nhất thế giới”.";
// From: IMAGE_BLOCK_MULTILINE_02
pub const MULTILINE_LINE_CAPTION_02: &str = "BẠCH ĐẰNG HẢI KHẨU\n\
    Sóc phong xuy hải khí lăng lăng,\n\
    Khinh khởi ngâm phàm quá Bạch Đằng.\n\
    Ngạc đoạn kình khoa sơn khúc khúc,\n\
    Qua trầm kích chiết ngạn tằng tằng.\n\
    Quan hà bách nhị do thiên thiết,\n\
    Hào kiệt công danh thử địa tằng.\n\
    Vãng sự hồi đầu ta dĩ hĩ,\n\
    Lâm lưu phủ cảnh ý nan thăng.\n\
    -- Ức Trai Nguyễn Trãi";

// From: IMAGE_BLOCK_MULTILINE_03
// Captions with **blank lines** (two consecutive newlines).
// Empty, results in no `Block` element at all.
pub const MULTILINE_LINE_CAPTION_03: &str = "\n\n";

// From: IMAGE_BLOCK_MULTI_LINGUAL
pub const MULTI_LINGUAL_CAPTION_01: &str = "Mount Fuji / 富士山, ふじさ, Fujisan / Núi Phú Sỹ";

// From: IMAGE_BLOCK_WIN_STYLE
// TO_DO: this is too fragmented, when implemented `_`, this test will change.
pub const WIN_STYLE_PATH_TEXT: &str = "\
    F:\\rust\\polyglot_pdf\\pdf_09_image_block\\text\\img - \
    Copy \\(2\\)\\ho-chi-minh-marius-moutet-19460914.png";
pub const WIN_STYLE_PATH_PARSED_TEXT: &str = r"F:\rust\polyglot_pdf\pdf_09_image_block\text\img - Copy (2)\ho-chi-minh-marius-moutet-19460914.png";

// From: IMAGE_BLOCK_ESCAPE_01
pub const ESCAPE_CAPTION_01: &str = "Mount Fuji / \\(富士山, ふじさ, \
    Fujisan\\) / \\[Núi Phú Sỹ\\]";
pub const ESCAPE_CAPTION_01_PARSED_TEXT: &str = "Mount Fuji / (富士山, ふじさ, \
    Fujisan) / [Núi Phú Sỹ]";

// From: IMAGE_BLOCK_ESCAPE_02
pub const ESCAPE_CAPTION_02: &str = "Mount Fuji\\! So Beautiful\\!";
pub const ESCAPE_CAPTION_02_PARSED_TEXT: &str = "Mount Fuji! So Beautiful!";

// From: IMAGE_BLOCK_ESCAPE_03
// Captions with **escaped newlines** (`\\n`).
pub const ESCAPE_CAPTION_03: &str = "Đây Là Con Chim Cassowary\\nÚc Đại Lợi";

// From: IMAGE_BLOCK_ESCAPE_04
// Captions containing: literal backslashes (`\\`),  escaped stars (`\*`), 
// escaped bangs (`\!`).
// <p>AÀÁ \ E Ê Ề \* Ù Ú Ụ \! Đ D</p>
pub const ESCAPE_CAPTION_04: &str = "AÀÁ \\ E Ê Ề \\* Ù Ú Ụ \\! Đ D";
pub const ESCAPE_CAPTION_04_PARSED_TEXT: &str = "AÀÁ \\ E Ê Ề * Ù Ú Ụ ! Đ D";

// From: IMAGE_BLOCK_ESCAPE_05
// Captions containing `]` at the very end (`\]`).
// `[ AÀÁ E Ê Ề ]`
pub const ESCAPE_CAPTION_05: &str = "\\[ AÀÁ E Ê Ề \\]";
pub const ESCAPE_CAPTION_05_PARSED_TEXT: &str = "[ AÀÁ E Ê Ề ]";

// From: IMAGE_BLOCK_EMPHASIS_01
//     Use IMAGE_BLOCK_MULTI_LINGUAL_CAPTION for clean text!
// `<strong><em>Mount Fuji</em> / <em>富士山, ふじさ, Fujisan</em> / <em>Núi Phú Sỹ</em></strong>`
pub const EMPHASIS_CAPTION_01: &str = "***Mount Fuji* / *富士山, ふじさ, \
    Fujisan* / *Núi Phú Sỹ***";
pub const EMPHASIS_CAPTION_01_PARSED_TEXT: &str = "Mount Fuji / 富士山, ふじさ, \
    Fujisan / Núi Phú Sỹ";

// From: IMAGE_BLOCK_NESTED_EMPHASIS_01
// `<em><strong>a <em>b</em> c</strong></em>`
pub const NESTED_EMPHASIS_CAPTION_01: &str = "***a *b* c***";
pub const NESTED_EMPHASIS_CAPTION_01_PARSED_TEXT: &str = "a b c";

// From: IMAGE_BLOCK_EMPHASIS_ESCAPE_01
// Captions containing both escapes and emphasis markers.
//
// Note: Rust sees "\\(Núi Phú Sỹ\\)" as `\(Núi Phú Sỹ\)` -- which is 
// escape for the following character. In this case `(` and `)`.
//
// `<strong><em>Mount Fuji</em> / <em>富士山, ふじさ, Fujisan</em> / <em>(Núi Phú Sỹ)</em></strong>`
pub const EMPHASIS_ESCAPE_CAPTION_01: &str = "***Mount Fuji* / *富士山, ふじさ, \
    Fujisan* / *\\(Núi Phú Sỹ\\)***";
pub const EMPHASIS_ESCAPE_CAPTION_01_PARSED_TEXT: &str = "Mount Fuji / 富士山, ふじさ, \
    Fujisan / (Núi Phú Sỹ)";

/// The following are to test [`md_parser::parser::delimiter::DelimiterParser`] 
/// implementations of Markdown's **can_open** (left‑flanking), and **can_close** 
/// (right‑flanking) rules.

// `<strong>Úc<em>Đại</em>Lợi</strong>`
pub const LEFT_RIGHT_FLANKING_01: &str = "**Úc*Đại*Lợi**";
pub const LEFT_RIGHT_FLANKING_01_PARSED_TEXT: &str = "ÚcĐạiLợi";

// Renders as `a*"b"*c` in normal font. 
// `a*"b"*c`
pub const LEFT_RIGHT_FLANKING_02: &str = "a*\"b\"*c";

// `foo<em>bar</em>`
pub const LEFT_RIGHT_FLANKING_03: &str = "foo*bar*";
pub const LEFT_RIGHT_FLANKING_03_PARSED_TEXT: &str = "foobar";

// `foo<em>bar</em>baz`
pub const LEFT_RIGHT_FLANKING_04: &str = "foo*bar*baz";
pub const LEFT_RIGHT_FLANKING_04_PARSED_TEXT: &str = "foobarbaz";

// `<em>foo <em>bar</em> baz</em>`
pub const LEFT_RIGHT_FLANKING_05: &str = "*foo *bar* baz*";
pub const LEFT_RIGHT_FLANKING_05_PARSED_TEXT: &str = "foo bar baz";

// Tests: nested matching / partial consumption / and stack backtracking.
// `<strong><em>a</em>b</strong>*`
pub const LEFT_RIGHT_FLANKING_06: &str = "***a*b***";
pub const LEFT_RIGHT_FLANKING_06_PARSED_TEXT: &str = "ab*";

// `<em>foo</em>`
pub const LEFT_RIGHT_FLANKING_07: &str = "*foo*";
pub const LEFT_RIGHT_FLANKING_07_PARSED_TEXT: &str = "foo";

// The MODULO_3_* are related also to:
//
//     LEFT_RIGHT_FLANKING_06 = "***a*b***";
//     EMPHASIS_ESCAPE_CAPTION_01 = "***Mount Fuji* / *富士山, ふじさ, Fujisan* / *\\(Núi Phú Sỹ\\)***";
//     LEFT_RIGHT_FLANKING_01 = "**Úc*Đại*Lợi**"; 
//
// `<em>a**b</em>`
pub const MODULO_3_01: &str = "*a**b*";
pub const MODULO_3_01_PARSED_TEXT: &str = "a**b";

// `**<em><strong>Hello<em>world</em></strong></em>`
pub const MODULO_3_02: &str = "*****Hello*world****";
pub const MODULO_3_02_PARSED_TEXT: &str = "**Helloworld";

// `<em><strong>a</strong>b</em>`    
pub const MODULO_3_03: &str = "***a**b*";
pub const MODULO_3_03_PARSED_TEXT: &str = "ab";

pub const TOKEN_LEXEME_AS_TEXT_01: &str = "Hello # not a ! header";

// markdown_parser_match_delimiters_problems_and_refactor.md
// `**<em>a <em><em>b</em> c</em></em>`.
pub const EDGE_CASE_NESTING_01: &str = "***a **b* c**";
pub const EDGE_CASE_NESTING_01_PARSED_TEXT: &str = "**a b c";

// markdown_parser_match_delimiters_problems_and_refactor.md
// `*<em><em>a <em>b</em></em> c</em>`
pub const EDGE_CASE_NESTING_02: &str = "***a *b** c*";
pub const EDGE_CASE_NESTING_02_PARSED_TEXT: &str = "*a b c";

// `<strong>a <em>b</em> c</strong>`
pub const EDGE_CASE_NESTING_03: &str = "**a *b* c**";
pub const EDGE_CASE_NESTING_03_PARSED_TEXT: &str = "a b c";

// `<strong><em>a</em> b</strong>`
pub const EDGE_CASE_NESTING_04: &str = "***a* b**";
pub const EDGE_CASE_NESTING_04_PARSED_TEXT: &str = "a b";

// `<em><em><strong>a</strong></em> b</em>`
pub const EDGE_CASE_NESTING_05: &str = "****a*** b*";
pub const EDGE_CASE_NESTING_05_PARSED_TEXT: &str = "a b";

// Example: 70, Markdown: "foo\n    # bar\n"; `foo\n# bar</p>\n`
// `foo\n<em># bar</em>\n`
pub const HEADER_EXAMPLE_70_VARIANT_01: &str = "foo\n    *# bar*\n";
pub const HEADER_EXAMPLE_70_VARIANT_01_PARSED_TEXT: &str = "foo\n# bar\n";
// `foo*\n# bar*\n`
pub const HEADER_EXAMPLE_70_VARIANT_02: &str = "foo*\n    # bar*\n";
pub const HEADER_EXAMPLE_70_VARIANT_02_PARSED_TEXT: &str = "foo*\n# bar*\n";
// `foo    # bar\n`
pub const HEADER_EXAMPLE_70_VARIANT_03: &str = "foo    # bar\n";

/// The following are used by `tests/test_parser.rs` only.
/// They are thematic and code block.
pub const THEMATIC_01: &str = "***";
pub const THEMATIC_02: &str = "****";
pub const THEMATIC_03: &str = "___";
pub const THEMATIC_04: &str = "____";
pub const THEMATIC_05: &str = "---";
pub const THEMATIC_06: &str = "----";
pub const THEMATIC_07: &str = "   ****"; // 3-leading spaces.
pub const THEMATIC_08: &str = "   ____"; // 3-leading spaces.
pub const THEMATIC_09: &str = "   ----"; // 3-leading spaces.
pub const THEMATIC_10: &str = "** ** ** ** **";
pub const THEMATIC_11: &str = "  *                    * *";
pub const THEMATIC_12: &str = " __ __ __ ";
pub const THEMATIC_13: &str = "  --     --- ---";
pub const THEMATIC_14: &str = "- -    -";
pub const THEMATIC_15: &str = "  _    _  _";
pub const THEMATIC_16: &str = "   ***\n____\n----    ";

pub const FALSE_THEMATIC_01: &str = "* ** *******  a *******";
pub const FALSE_THEMATIC_02: &str = "** ** ** ** ** _";
pub const FALSE_THEMATIC_03: &str = "** ** ** ** ** -";

// `--- --- a`.
pub const FALSE_THEMATIC_04: &str = "  --- --- a";
pub const FALSE_THEMATIC_04_PARSED_TEXT: &str = "--- --- a";

pub const FALSE_THEMATIC_05: &str = " __";
pub const FALSE_THEMATIC_05_PARSED_TEXT: &str = "__";

// TO_DO: Not included in test yet.
pub const FALSE_THEMATIC_06: &str = " ___          f";

// `<pre><code>****</code></pre>`
pub const CODE_BLOCK_01: &str = "    ****";
pub const CODE_BLOCK_01_PARSED_CODE: &str = "****";

// `<pre><code> ****</code></pre>`
pub const CODE_BLOCK_02: &str = "     ****";
pub const CODE_BLOCK_02_PARSED_CODE: &str = " ****";

// `<pre><code>self.current += 1;</code></pre><p>// This is a comment.</p>`
pub const CODE_BLOCK_03: &str = "    self.current += 1;\n// This is a comment.";
pub const CODE_BLOCK_03_PARSED_CODE: &str = "self.current += 1;\n";
pub const CODE_BLOCK_03_PARSED_TEXT: &str = "// This is a comment.";

/// The following are used by `tests/test_parser.rs` only.
pub const IMAGE_BLOCK_SPACE_IN_PATH: &str = "![a](./img/my image.png)";
pub const IMAGE_BLOCK_SPACE_IN_PATH_CAPTION: &str = "a";
pub const IMAGE_BLOCK_SPACE_IN_PATH_PATH: &str = "./img/my image.png";

pub const IMAGE_BLOCK_PARENS_IN_PATH_01: &str = "![a](./img/(weird).png)";
pub const IMAGE_BLOCK_PARENS_IN_PATH_01_CAPTION: &str = "a";
pub const IMAGE_BLOCK_PARENS_IN_PATH_01_PATH: &str = "./img/(weird).png";

pub const IMAGE_BLOCK_PARENS_IN_PATH_02: &str = "![a](./img/(weird)(1).png)";
pub const IMAGE_BLOCK_PARENS_IN_PATH_02_CAPTION: &str = "a";
pub const IMAGE_BLOCK_PARENS_IN_PATH_02_PATH: &str = "./img/(weird)(1).png";

pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_01: &str = "![a [nested] text](img.png)";
pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_01_CAPTION: &str = "a [nested] text";
pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_01_PATH: &str = "img.png";

pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_02: &str = "![a [[nested]] text](img.png)";
pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_02_CAPTION: &str = "a [[nested]] text";
pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_02_PATH: &str = "img.png";

pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_03: &str = "![a [[nested]] [nested again] \
    text](img.png)";
pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_03_CAPTION: &str = "a [[nested]] \
    [nested again] text";
pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_03_PATH: &str = "img.png";

// From:
//     pub const IMAGE_BLOCK_ESCAPE_01: &str = "![Mount Fuji / \\(富士山, ふじさ, \
//        Fujisan\\) / \\[Núi Phú Sỹ\\]](./img/fujisan.png)";
// with all escape markers removed. The result should be the same as with 
// escape markers in place. Used original parsed caption and path in test.
//
// pub const IMAGE_BLOCK_ESCAPE_01_CAPTION: &str = "Mount Fuji / (富士山, ふじさ, \
//    Fujisan) / [Núi Phú Sỹ]";
// pub const IMAGE_BLOCK_ESCAPE_01_PATH: &str = "./img/fujisan.png";
pub const IMAGE_BLOCK_MIXED_BRACKETS_PARENS_01: &str = "![Mount Fuji / \
    (富士山, ふじさ, Fujisan) / [Núi Phú Sỹ]](./img/fujisan.png)";

pub const IMAGE_BLOCK_PARENS_IN_PATH_INVALID_01: &str = "![a](./img/(weird).png";

pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_INVALID_01: &str = "![a [[nested]] \
    text(img.png)";

pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_INVALID_02: &str = "test\n![a [[nested]] \
    text(img.png)";
pub const IMAGE_BLOCK_BRACKETS_IN_CAPTION_INVALID_02_PARSED_TEXT: &str = "![a \
    [[nested]] text(img.png)";


/* 
TO_DO: Test for when "Opener Bottom" Optimisation implemented:

"*a *b *c *d *e *f *g [a long text with 10000 words but no closing brackets or asterisks]"

Internal development document `markdown_21_parser_initial_version_final_review.md`.

Currently, the parser produces correct result that matches 
https://spec.commonmark.org/dingus/ result. 
*/

pub const TEST_MARKDOWNS: [&str; 146] = [
    HEADER_02_TEXT,                              // 00
    TOKEN_LEXEME_AS_TEXT_01,                     // 01
    HEADER_01,                                   // 02
    HEADER_02,                                   // 03
    HEADER_03,                                   // 04
    HEADER_04,                                   // 05
    HEADER_05,                                   // 06
    HEADER_06,                                   // 07
    HASH_ESCAPE_01,                              // 08
    HASH_ESCAPE_02,                              // 09
    HEADER_HASH_ESCAPE_01,                       // 10
    ASTERISK_01,                                 // 11
    ASTERISK_02,                                 // 12
    ASTERISK_03,                                 // 13
    ASTERISK_04,                                 // 14
    ASTERISK_05,                                 // 15
    ASTERISK_06,                                 // 16
    ASTERISK_07,                                 // 17
    ASTERISK_08,                                 // 18
    ASTERISK_09,                                 // 19
    ASTERISK_10,                                 // 20
    ASTERISK_11,                                 // 21
    ASTERISK_12,                                 // 22
    ASTERISK_20,                                 // 23
    ASTERISK_21,                                 // 24
    ASTERISK_22,                                 // 25
    ASTERISK_23,                                 // 26
    ASTERISK_24,                                 // 27
    ASTERISK_25,                                 // 28
    ASTERISK_26,                                 // 29
    ASTERISK_13,                                 // 30
    ASTERISK_14,                                 // 31
    EMPHASIS_BOLD_INSIDE_ITALIC_01,              // 32
    EMPHASIS_BOLD_INSIDE_ITALIC_02,              // 33
    ASTERISK_15,                                 // 34
    ASTERISK_16,                                 // 35
    ASTERISK_17,                                 // 36
    ASTERISK_18,                                 // 37
    ASTERISK_19,                                 // 38
    RECURRING_ESCAPE_01,                         // 39
    RECURRING_ESCAPE_02,                         // 40
    ESCAPE_NEWLINE_01,                           // 41
    ESCAPE_INSIDE_EMPHASIS_01,                   // 42
    EMPHASIS_ADJACENT_ESCAPE_01,                 // 43
    EMPHASIS_UNEVEN_TOKEN_01,                    // 44
    EMPHASIS_UNEVEN_TOKEN_02,                    // 45
    EMPHASIS_UNEVEN_TOKEN_03,                    // 46
    EMPHASIS_UNEVEN_TOKEN_04,                    // 47
    IMAGE_BLOCK_01,                              // 48
    IMAGE_BLOCK_02,                              // 49
    IMAGE_BLOCK_03,                              // 50
    IMAGE_BLOCK_04,                              // 51
    IMAGE_BLOCK_MULTILINE_01,                    // 52
    IMAGE_BLOCK_MULTILINE_02,                    // 53
    IMAGE_BLOCK_MULTILINE_03,                    // 54
    IMAGE_BLOCK_MULTI_LINGUAL,                   // 55
    IMAGE_BLOCK_05,                              // 56
    IMAGE_BLOCK_06,                              // 57
    IMAGE_BLOCK_WIN_STYLE,                       // 58
    IMAGE_BLOCK_ESCAPE_01,                       // 59
    IMAGE_BLOCK_ESCAPE_02,                       // 60
    IMAGE_BLOCK_ESCAPE_03,                       // 61
    IMAGE_BLOCK_ESCAPE_04,                       // 62
    IMAGE_BLOCK_ESCAPE_05,                       // 63
    IMAGE_BLOCK_EMPHASIS_01,                     // 64
    IMAGE_BLOCK_NESTED_EMPHASIS_01,              // 65
    IMAGE_BLOCK_EMPHASIS_ESCAPE_01,              // 66
    IMAGE_BLOCK_MULTI_ITEMS_01,                  // 67
    IMAGE_BLOCK_MULTI_ITEMS_02,                  // 68
    MULTILINE_LINE_CAPTION_01,                   // 69
    MULTILINE_LINE_CAPTION_02,                   // 70
    MULTILINE_LINE_CAPTION_03,                   // 71
    MULTI_LINGUAL_CAPTION_01,                    // 72
    WIN_STYLE_PATH_TEXT,                         // 73
    ESCAPE_CAPTION_01,                           // 74
    ESCAPE_CAPTION_02,                           // 75
    ESCAPE_CAPTION_03,                           // 76
    ESCAPE_CAPTION_04,                           // 77
    ESCAPE_CAPTION_05,                           // 78
    EMPHASIS_CAPTION_01,                         // 79
    NESTED_EMPHASIS_CAPTION_01,                  // 80
    EMPHASIS_ESCAPE_CAPTION_01,                  // 81
    LEFT_RIGHT_FLANKING_01,                      // 82
    LEFT_RIGHT_FLANKING_02,                      // 83
    LEFT_RIGHT_FLANKING_03,                      // 84
    LEFT_RIGHT_FLANKING_04,                      // 85
    LEFT_RIGHT_FLANKING_05,                      // 86
    LEFT_RIGHT_FLANKING_06,                      // 87
    LEFT_RIGHT_FLANKING_07,                      // 88
    MODULO_3_01,                                 // 89
    MODULO_3_02,                                 // 90
    MODULO_3_03,                                 // 91
    HEADER_INVALID_01,                           // 92
    HEADER_INVALID_02,                           // 93
    HEADER_INVALID_03,                           // 94
    HEADER_INVALID_04,                           // 95
    IMAGE_BLOCK_INVALID_01,                      // 96
    IMAGE_BLOCK_INVALID_02,                      // 97
    IMAGE_BLOCK_INVALID_03,                      // 98
    IMAGE_BLOCK_INVALID_04,                      // 99
    IMAGE_BLOCK_INVALID_05,                      // 100
    IMAGE_BLOCK_INVALID_06,                      // 101
    IMAGE_BLOCK_INVALID_07,                      // 102
    IMAGE_BLOCK_INVALID_08,                      // 103
    EDGE_CASE_NESTING_01,                        // 104
    EDGE_CASE_NESTING_02,                        // 105
    EDGE_CASE_NESTING_03,                        // 106
    EDGE_CASE_NESTING_04,                        // 107
    EDGE_CASE_NESTING_05,                        // 108
    HEADER_EXAMPLE_70_VARIANT_01,                // 109
    HEADER_EXAMPLE_70_VARIANT_02,                // 110
    HEADER_EXAMPLE_70_VARIANT_03,                // 111
    IMAGE_BLOCK_ADJACENT_TEXT_01,                // 112
    THEMATIC_01,                                 // 113
    THEMATIC_02,                                 // 114
    THEMATIC_03,                                 // 115
    THEMATIC_04,                                 // 116
    THEMATIC_05,                                 // 117
    THEMATIC_06,                                 // 118
    THEMATIC_07,                                 // 119
    THEMATIC_08,                                 // 120
    THEMATIC_09,                                 // 121
    THEMATIC_10,                                 // 122
    THEMATIC_11,                                 // 123
    THEMATIC_12,                                 // 124
    THEMATIC_13,                                 // 125
    THEMATIC_14,                                 // 126
    THEMATIC_15,                                 // 127
    THEMATIC_16,                                 // 128
    FALSE_THEMATIC_01,                           // 129
    FALSE_THEMATIC_02,                           // 130
    FALSE_THEMATIC_03,                           // 131
    FALSE_THEMATIC_04,                           // 132
    FALSE_THEMATIC_05,                           // 133
    CODE_BLOCK_01,                               // 134
    CODE_BLOCK_02,                               // 135
    CODE_BLOCK_03,                               // 136
    IMAGE_BLOCK_SPACE_IN_PATH,                   // 137
    IMAGE_BLOCK_PARENS_IN_PATH_01,               // 138
    IMAGE_BLOCK_PARENS_IN_PATH_02,               // 139
    IMAGE_BLOCK_BRACKETS_IN_CAPTION_01,          // 140
    IMAGE_BLOCK_BRACKETS_IN_CAPTION_02,          // 141
    IMAGE_BLOCK_BRACKETS_IN_CAPTION_03,          // 142
    IMAGE_BLOCK_PARENS_IN_PATH_INVALID_01,       // 143
    IMAGE_BLOCK_BRACKETS_IN_CAPTION_INVALID_01,  // 144
    IMAGE_BLOCK_BRACKETS_IN_CAPTION_INVALID_02,  // 145
];